export {
    BOOKING_STATUS,
    BOOKING_COLLECTION,
    BOOKED_SLOTS_COLLECTION,
    normalizeBookingData,
    createBooking,
    checkSlotAvailability,
    reserveTimeSlot,
    confirmTimeSlot,
    cancelTimeSlot,
    updateBookingStatus,
    rescheduleBooking,
    confirmBooking,
    cancelBooking,
    completeBooking,
    markNoShow,
    fetchShopBookings,
    fetchCustomerBookings,
    fetchBookingById,
    subscribeToShopBookings,
    subscribeToCustomerBookings,
    getAvailableTimeSlots,
    generateTimeSlots,
    validateBookingOverlap
} from './bookingService';
